//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.24 at 07:38:08 PM CET 
//


package net.opengis.gml.v_3_2_1;

import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlType;
import com.sun.xml.internal.bind.annotation.OverrideAnnotationOf;


/**
 * <p>Java class for GenericMetaDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GenericMetaDataType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/gml/3.2}AbstractMetaDataType">
 *       &lt;sequence>
 *         &lt;any processContents='lax' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GenericMetaDataType")
public class GenericMetaDataType
    extends AbstractMetaDataType
{

    @XmlMixed
    @XmlAnyElement(lax = true)
    @OverrideAnnotationOf
    protected List<Object> contentOverrideForGenericMetaDataType;

    public boolean isSetcontentOverrideForGenericMetaDataType() {
        return ((this.contentOverrideForGenericMetaDataType!= null)&&(!this.contentOverrideForGenericMetaDataType.isEmpty()));
    }

}
